export const TOGGLE_SWITCH = 'TOGGLE_SWITCH';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_WEATHER_FORECAST = 'GET_WEATHER_FORECAST';
export const GET_WEATHER = 'GET_WEATHER';
